### ISSUE TITLE
发现一个markdown在GitHub显示的问题

### ISSUE THREAD

**Issue by zzqxaut** [cubxxw/awesome-cs-course#4]
markdown文件夹数学公式文件中，部分\left无法识别，没有显示渲染后的公式，我也遇到这个问题了，不知道是咋回事

**Comment by 3293172751** [comment]
👣 存在数学公式无法正常显示问题，强烈推荐[📐 MathJax Plugin for Github](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima) 插件使用。
